### ISSUE TITLE
Design document comments

### ISSUE THREAD

**Issue by joseph-hellerstein** [rguptauw/pybcoin#1]
I think that you have all of the content required for an initial draft of the functional and component specifications. My main feedback is that you've intermixed the two. For example, in the section on functional requirements, you say that one of the requirements is to create a database. This is not a functional requirement; this is a statement about a component.

Please revise your document so that the functional section describes the user interactions, and you put all of the component discussion into the components section.

One more small thing. Please put a PDF of the word document in the docs folder so that it is readable without using MSWord.

**Comment by TejasJagadeesh** [comment]
Thank you for the review comments. I have uploaded updated file "FDD_Bitcoin_Predict_v2.pdf" for review.
